spring.application.name=BookAPI
# 1. The Connection URL (Server address + Database name)
spring.datasource.url=jdbc:mysql://localhost:3306/bookAPI

# 2. Your MySQL Credentials
spring.datasource.username=root
spring.datasource.password=root123

# 3. The Driver Class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate Settings (Tells Hibernate to update tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true